### ISSUE TITLE
CPAN pull req challenge

### ISSUE THREAD

**Issue by kanatohodets** [rwstauner/Config-MVP-Slicer#1]
Hiya Randy,

neilb + scripts assigned me to Config::MVP::Slicer for the CPAN pull request challenge (http://blogs.perl.org/users/neilb/2014/12/take-the-2015-cpan-pull-request-challenge.html) -- I spotted some TODOs in the code, but I wanted to ask if there's anything in particular you've had in mind but never quite had the tuits for.

No worries if you have no plans or consider the module finished -- I'll play around and teach myself Dist::Zilla, then perhaps send a pull req for one of the TODOs.

Thanks!

**Comment by rwstauner** [comment]
I appreciate the interest but I'm not sure what to suggest.

I looked at the TODO comments in the code, and most of them look like things I wasn't sure about when first writing it, but since I haven't heard any issues in the last two years I'd guess they're not really concerns.

I won't be offended if you want to ask neilb for another dist.
but if you want to stick with this one feel free to look around.
If you come up with questions that'd be a good candidate for documentation patches.
Or we could perhaps determine that the TODO comments are not warranted and could be removed.

I do see one that looks funny... There's a TODO that says "should we be dying here?"... and the next line it does in fact `croak`, and then there's a `next`.  I'm pretty sure that `next` will never get called, and i think the croak is appropriate, so those two lines could be removed.

Coverage is pretty good, but there is room for improvement, so you're welcome to work on that as well.

**Comment by rwstauner** [comment]
Another thing we could do is get this on travis (and coveralls).
It's something I've been meaning to do with my dists but just haven't yet.
There are a couple of Dist::Zilla plugins for doing it more automatically but I haven't gotten around to picking/configuring those yet.  There's also https://github.com/travis-perl/helpers which looks pretty handy, but again i haven't learned/used that yet either.

This is kind of a niche module in that it has a limited use case:
it adds functionality to config files read by Config::MVP [which is used by less than half a dozen apps](https://metacpan.org/requires/distribution/Config-MVP), so probably 95% of its use is `dist.ini` files for Dist::Zilla.

So if you poke around this and related modules a bit you might find something helpful to add to the  DESCRIPTION or maybe add a SEE ALSO section to link to some of the related dists.
